/**
 * Breadcrumb Translation Helper
 * Maps route names to their corresponding translation keys
 */

export const breadcrumbTranslationMap = {
  'dashboard': 'common.breadcrumbs.dashboard',
  'Inventory': 'common.breadcrumbs.inventory',
  'All Products': 'common.breadcrumbs.allProducts',
  'All Services': 'common.breadcrumbs.allServices',
  'CreateProduct': 'common.breadcrumbs.createProduct',
  'CreateService': 'common.breadcrumbs.createService',
  'EditProduct': 'common.breadcrumbs.editProduct',
  'EditService': 'common.breadcrumbs.editService',
  'ProductCategories': 'common.breadcrumbs.productCategories',
  'CreateProductCategory': 'common.breadcrumbs.createProductCategory',
  'EditProductCategory': 'common.breadcrumbs.editProductCategory',
  'Attributes': 'common.breadcrumbs.attributes',
  'CreateAttribute': 'common.breadcrumbs.createAttribute',
  'EditAttribute': 'common.breadcrumbs.editAttribute',
  'Brands': 'common.breadcrumbs.brands',
  'StockAdjustment': 'common.breadcrumbs.stockAdjustment',
  'CreateStockAdjustment': 'common.breadcrumbs.createStockAdjustment',
  'ViewStockAdjustment': 'common.breadcrumbs.viewStockAdjustment',
  'ListStockCount': 'common.breadcrumbs.listStockCount',
  'CreateStockCount': 'common.breadcrumbs.createStockCount',
  'ViewStockCount': 'common.breadcrumbs.viewStockCount',
  'EditStockCount': 'common.breadcrumbs.editStockCount',
  'Pos': 'common.breadcrumbs.pos',
  'Register': 'common.breadcrumbs.register',
  'Invoices': 'common.breadcrumbs.invoices',
  'ReturnInvoices': 'common.breadcrumbs.returnInvoices',
  'Register Open': 'common.breadcrumbs.registerOpen',
  'Register Close': 'common.breadcrumbs.registerClose',
  'Quotation': 'common.breadcrumbs.quotation',
  'Quotations': 'common.breadcrumbs.quotations',
  'Customers': 'common.breadcrumbs.customers',
  'Suppliers': 'common.breadcrumbs.suppliers',
  'Supplier': 'common.breadcrumbs.supplier',
  'List Supplier': 'common.breadcrumbs.listSupplier',
  'Create supplier': 'common.breadcrumbs.createSupplier',
  'Edit Supplier': 'common.breadcrumbs.editSupplier',
  'Purchasing': 'common.breadcrumbs.purchasing',
  'List Purchase Invoice': 'common.breadcrumbs.listPurchaseInvoice',
  'Create Purchase Invoice': 'common.breadcrumbs.createPurchaseInvoice',
  'List Purchase Return Invoice': 'common.breadcrumbs.listPurchaseReturnInvoice',
  'Create Purchase Return Invoice': 'common.breadcrumbs.createPurchaseReturnInvoice',
  'Reporting': 'common.breadcrumbs.reporting',
  'ReportingDashboard': 'common.breadcrumbs.reportingDashboard',
  'InventoryReport': 'common.breadcrumbs.inventoryReport',
  'Inventory Leve Report': 'common.breadcrumbs.inventoryLeveReport',
  'Products Stock Value': 'common.breadcrumbs.productsStockValue',
  'Product Dead Items': 'common.breadcrumbs.productDeadItems',
  'Top Selling Product Level': 'common.breadcrumbs.topSellingProductLevel',
  'Stock Count Report': 'common.breadcrumbs.stockCountReport',
  'Stock Adjustment Report': 'common.breadcrumbs.stockAdjustmentReport',
  'SalesReport': 'common.breadcrumbs.salesReport',
  'DailyMonthlySalesReport': 'common.breadcrumbs.dailyMonthlySalesReport',
  'CustomerPurchaseHistoryReport': 'common.breadcrumbs.customerPurchaseHistoryReport',
  'SalesPerformanceReport': 'common.breadcrumbs.salesPerformanceReport',
  'SalesPerformanceByServicesReport': 'common.breadcrumbs.salesPerformanceByServicesReport',
  'DiscountsReport': 'common.breadcrumbs.discountsReport',
  'ProductProfitReport': 'common.breadcrumbs.productProfitReport',
  'PurchaseReport': 'common.breadcrumbs.purchaseReport',
  'PurchaseSummaryReport': 'common.breadcrumbs.purchaseSummaryReport',
  'Supplier Wise Purchase Report': 'common.breadcrumbs.supplierWisePurchaseReport',
  'Return To Supplier Report': 'common.breadcrumbs.returnToSupplierReport',
  'Supplier Wise Payment': 'common.breadcrumbs.supplierWisePayment',
  'StockLevelsReport': 'common.breadcrumbs.stockLevelsReport',
  'WorkerPerformanceReport': 'common.breadcrumbs.workerPerformanceReport',
  'TaxReport': 'common.breadcrumbs.taxReport',
  'TaxReporting': 'common.breadcrumbs.taxReporting',
  'TrialBalanceReport': 'common.breadcrumbs.trialBalanceReport',
  'BalanceSheetReport': 'common.breadcrumbs.balanceSheetReport',
  'ProfitLossReport': 'common.breadcrumbs.profitLossReport',
  'Accounting': 'common.breadcrumbs.accounting',
  'Account': 'common.breadcrumbs.account',
  'Chart Of Account': 'common.breadcrumbs.chartOfAccount',
  'Create Chart Of Account': 'common.breadcrumbs.createChartOfAccount',
  'Edit Chart Of Account': 'common.breadcrumbs.editChartOfAccount',
  'View Chart Of Account': 'common.breadcrumbs.viewChartOfAccount',
  'Journal Entries': 'common.breadcrumbs.journalEntries',
  'Create Journal Entry': 'common.breadcrumbs.createJournalEntry',
  'View Journal Entry': 'common.breadcrumbs.viewJournalEntry',
  'Edit Journal Entry': 'common.breadcrumbs.editJournalEntry',
  'Expenses': 'common.breadcrumbs.expenses',
  'Create Expense': 'common.breadcrumbs.createExpense',
  'General Ledger': 'common.breadcrumbs.generalLedger',
  'View General Ledger': 'common.breadcrumbs.viewGeneralLedger',
  'Setting': 'common.breadcrumbs.setting',
  'TaxManagement': 'common.breadcrumbs.taxManagement',
  'UserManagement': 'common.breadcrumbs.userManagement',
  'SubscriptionManagement': 'common.breadcrumbs.subscriptionManagement',
  'CompanyProfile': 'common.breadcrumbs.companyProfile',
  'GeneralSettings': 'common.breadcrumbs.generalSettings',
  'SaleTarget': 'common.breadcrumbs.saleTarget',
  'BarcodeScanner': 'common.breadcrumbs.barcodeScanner',
  'Jobs': 'common.breadcrumbs.jobs',
  'EditInvoice': 'common.breadcrumbs.editInvoice',
  'ReturnInvoice': 'common.breadcrumbs.returnInvoice',
  'Access Denied': 'common.breadcrumbs.accessDenied',
  'SuperAdminDashboard': 'common.breadcrumbs.superAdminDashboard',
};

/**
 * Translates a breadcrumb route name to its corresponding translation key
 * @param {string} name - The route name to translate
 * @returns {string} - The translation key or formatted name if not found
 */
export const getBreadcrumbTranslationKey = (name) => {
  if (!name || name === '/admin' || name === 'ReportingDashboard') {
    return '';
  }
  
  return breadcrumbTranslationMap[name] || null;
};

