/**
 * Static sidebar tree (order matches product spec). page_name must match Vue route `name` for active states.
 */
export type StaticSideMenuItem = {
  id: string;
  menu_name: string;
  url: string | null;
  icon: string;
  title: string;
  page_name: string | null;
  status: boolean;
  permissions: string[] | null;
  is_parent: boolean;
  /** Lowercase module key matched against package allowed_modules. null = always visible. */
  module_key: string | null;
  children: StaticSideMenuItem[];
};

export const STATIC_SHOP_SIDE_MENU: StaticSideMenuItem[] = [
  {
    id: "dashboard",
    menu_name: "Dashboard",
    url: "/admin",
    icon: "Home",
    title: "Dashboard",
    page_name: "dashboard",
    status: true,
    permissions: null,
    is_parent: false,
    module_key: null, // always visible
    children: [],
  },
  {
    id: "subscriptions",
    menu_name: "Subscriptions",
    url: "/package-selection",
    icon: "Package",
    title: "Subscriptions",
    page_name: "PackageSelection",
    status: true,
    // Only owners with billing rights should see Subscriptions. Cashiers /
    // workers with `settings:List` only do not get this entry.
    permissions: ["settings:Update"],
    is_parent: false,
    module_key: null,
    children: [],
  },
  {
    id: "inventory",
    menu_name: "Inventory",
    url: "/inventory/products",
    icon: "Inbox",
    title: "Inventory",
    page_name: null,
    status: true,
    permissions: ["products:List"],
    is_parent: false,
    module_key: "inventory",
    children: [
      {
        id: "inv-products",
        menu_name: "Products",
        url: "/inventory/products",
        icon: "Box",
        title: "Products",
        page_name: "All Products",
        status: true,
        permissions: ["products:List"],
        is_parent: false,
        module_key: "inventory",
        children: [],
      },
      {
        id: "inv-services",
        menu_name: "Services",
        url: "/inventory/services",
        icon: "Wrench",
        title: "Services",
        page_name: "All Services",
        status: true,
        // Service catalog management — requires write on products.
        permissions: ["products:Update"],
        is_parent: false,
        module_key: "inventory",
        children: [],
      },
      {
        id: "inv-category",
        menu_name: "Category",
        url: "/inventory/categories",
        icon: "LayoutGrid",
        title: "Category",
        page_name: "ProductCategories",
        status: true,
        permissions: ["products:Update"],
        is_parent: false,
        module_key: "inventory",
        children: [],
      },
      {
        id: "inv-attributes",
        menu_name: "Attributes",
        url: "/inventory/attributes",
        icon: "Bolt",
        title: "Attributes",
        page_name: "Attributes",
        status: true,
        permissions: ["products:Update"],
        is_parent: false,
        module_key: "inventory",
        children: [],
      },
      {
        id: "inv-brands",
        menu_name: "Brands",
        url: "/inventory/brands",
        icon: "Tag",
        title: "Brands",
        page_name: "Brands",
        status: true,
        permissions: ["products:Update"],
        is_parent: false,
        module_key: "inventory",
        children: [],
      },
      {
        id: "inv-stock-adj",
        menu_name: "Stock Adjustment",
        url: "/inventory/stock-adjustment",
        icon: "Layers",
        title: "Stock Adjustment",
        page_name: "StockAdjustment",
        status: true,
        permissions: ["products:Update"],
        is_parent: false,
        module_key: "inventory",
        children: [],
      },
      {
        id: "inv-stock-count",
        menu_name: "Stock Count",
        url: "/inventory/stock-count",
        icon: "Container",
        title: "Stock Count",
        page_name: "ListStockCount",
        status: true,
        permissions: ["products:Update"],
        is_parent: false,
        module_key: "inventory",
        children: [],
      },
    ],
  },
  {
    id: "pos",
    menu_name: "POS",
    url: "/pos/register",
    icon: "Monitor",
    title: "POS",
    page_name: null,
    status: true,
    permissions: ["invoices:List", "customers:List"],
    is_parent: false,
    module_key: "pos",
    children: [
      {
        id: "pos-registers",
        menu_name: "Daily Till",
        url: "/pos/register",
        icon: "BookOpenText",
        title: "Daily Till",
        page_name: "Register",
        status: true,
        permissions: ["register:Open"],
        is_parent: false,
        module_key: "pos",
        children: [],
      },
      {
        id: "pos-jobs",
        menu_name: "Jobs",
        url: "/pos/jobs",
        icon: "Briefcase",
        title: "Jobs",
        page_name: "Jobs",
        status: true,
        permissions: ["jobs:List"],
        is_parent: false,
        module_key: "pos",
        children: [],
      },
      {
        id: "pos-bookings",
        menu_name: "Bookings",
        url: "/pos/bookings",
        icon: "CalendarClock",
        title: "Bookings",
        page_name: "Bookings",
        status: true,
        permissions: ["booking:List"],
        is_parent: false,
        module_key: "pos",
        children: [],
      },
      {
        id: "pos-invoices",
        menu_name: "Invoices",
        url: "/pos/invoices",
        icon: "ScrollText",
        title: "Invoices",
        page_name: "Invoices",
        status: true,
        permissions: ["invoices:List"],
        is_parent: false,
        module_key: "pos",
        children: [],
      },
      {
        id: "pos-customers",
        menu_name: "Customers",
        url: "/pos/customers",
        icon: "Users",
        title: "Customers",
        page_name: "Customers",
        status: true,
        permissions: ["customers:List"],
        is_parent: false,
        module_key: "pos",
        children: [],
      },
      {
        id: "pos-return",
        menu_name: "Sales Return",
        url: "/pos/return-invoices",
        icon: "Undo2",
        title: "Sales Return",
        page_name: "ReturnInvoices",
        status: true,
        permissions: ["saleReturn:List"],
        is_parent: false,
        module_key: "pos",
        children: [],
      },
    ],
  },
  {
    id: "purchasing",
    menu_name: "Purchasing",
    url: "/purchasing/supplier",
    icon: "ShoppingBag",
    title: "Purchasing",
    page_name: null,
    status: true,
    permissions: ["suppliers:List"],
    is_parent: false,
    module_key: "purchasing",
    children: [
      {
        id: "pur-supplier",
        menu_name: "Supplier",
        url: "/purchasing/supplier",
        icon: "SendToBack",
        title: "Supplier",
        page_name: "List Supplier",
        status: true,
        permissions: ["suppliers:List"],
        is_parent: false,
        module_key: "purchasing",
        children: [],
      },
      {
        id: "pur-invoice",
        menu_name: "Purchase Invoice",
        url: "/purchasing/invoice",
        icon: "Scroll",
        title: "Purchase Invoice",
        page_name: "List Purchase Invoice",
        status: true,
        permissions: ["suppliers:List"],
        is_parent: false,
        module_key: "purchasing",
        children: [],
      },
      {
        id: "pur-return",
        menu_name: "Purchase Return",
        url: "/purchasing/invoice/return",
        icon: "FileSymlink",
        title: "Purchase Return",
        page_name: "List Purchase Return Invoice",
        status: true,
        permissions: ["suppliers:Delete"],
        is_parent: false,
        module_key: "purchasing",
        children: [],
      },
    ],
  },
  {
    id: "settings",
    menu_name: "Settings",
    url: "/setting/tax",
    icon: "Settings",
    title: "Settings",
    page_name: "TaxManagement",
    status: true,
    permissions: ["settings:List"],
    is_parent: false,
    module_key: null,
    children: [],
  },
  {
    id: "reporting",
    menu_name: "Reporting",
    url: "/reporting",
    icon: "SquareKanban",
    title: "Reporting",
    page_name: "ReportingDashboard",
    status: true,
    permissions: ["generalLedger:List"],
    is_parent: false,
    module_key: "reporting",
    children: [],
  },
  {
    id: "accounting",
    menu_name: "Accounting",
    url: "/account/chart-of-accounts",
    icon: "SquareUserRound",
    title: "Accounting",
    page_name: null,
    status: true,
    permissions: ["chartOfAccounts:List", "journalEntries:List", "expenses:List", "generalLedger:List"],
    is_parent: false,
    module_key: "accounting",
    children: [
      {
        id: "acc-coa",
        menu_name: "Chart of Accounts",
        url: "/account/chart-of-accounts",
        icon: "Book",
        title: "Chart of Accounts",
        page_name: "Chart Of Account",
        status: true,
        permissions: ["chartOfAccounts:List"],
        is_parent: false,
        module_key: "accounting",
        children: [],
      },
      {
        id: "acc-je",
        menu_name: "Journal Entries",
        url: "/account/journal-entries",
        icon: "Activity",
        title: "Journal Entries",
        page_name: "Journal Entries",
        status: true,
        permissions: ["journalEntries:List"],
        is_parent: false,
        module_key: "accounting",
        children: [],
      },
      {
        id: "acc-exp",
        menu_name: "Expenses",
        url: "/account/expenses",
        icon: "Receipt",
        title: "Expenses",
        page_name: "Expenses",
        status: true,
        permissions: ["expenses:List"],
        is_parent: false,
        module_key: "accounting",
        children: [],
      },
      {
        id: "acc-gl",
        menu_name: "General Ledger",
        url: "/account/general-ledger",
        icon: "BookMinus",
        title: "General Ledger",
        page_name: "General Ledger",
        status: true,
        permissions: ["generalLedger:List"],
        is_parent: false,
        module_key: "accounting",
        children: [],
      },
    ],
  },
];

export const STATIC_SUPERADMIN_SIDE_MENU: StaticSideMenuItem[] = [
  {
    id: "sa-dash",
    menu_name: "Dashboard",
    url: "/superadmin/dashboard",
    icon: "LayoutDashboard",
    title: "Dashboard",
    page_name: "SuperAdminDashboard",
    status: true,
    permissions: null,
    is_parent: false,
    children: [],
  },
  {
    id: "sa-shops",
    menu_name: "Shops",
    url: "/superadmin/shops",
    icon: "Store",
    title: "Shops",
    page_name: "SuperAdminShops",
    status: true,
    permissions: null,
    is_parent: false,
    children: [],
  },
];

export const STATIC_PRODUCT_OWNER_SIDE_MENU: StaticSideMenuItem[] = [
  {
    id: "po-dash",
    menu_name: "Dashboard",
    url: "/product-owner/dashboard",
    icon: "LayoutDashboard",
    title: "Dashboard",
    page_name: "ProductOwnerDashboard",
    status: true,
    permissions: null,
    is_parent: false,
    children: [],
  },
  {
    id: "po-superadmins",
    menu_name: "Super Admins",
    url: "/product-owner/super-admins",
    icon: "Users",
    title: "Super Admins",
    page_name: "ProductOwnerSuperAdmins",
    status: true,
    permissions: null,
    is_parent: false,
    children: [],
  },
  {
    id: "po-packages",
    menu_name: "Packages",
    url: "/product-owner/packages",
    icon: "Package",
    title: "Packages",
    page_name: "ProductOwnerPackages",
    status: true,
    permissions: null,
    is_parent: false,
    children: [],
  },
];
